language: ruby
sudo: false
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
